export type Difficulty = "easy" | "medium" | "hard";

export interface WordEntry {
  word: string;
  category: string;
  difficulty: Difficulty;
}

const wordBank: WordEntry[] = [
  // Easy
  { word: "cat", category: "Animals", difficulty: "easy" },
  { word: "dog", category: "Animals", difficulty: "easy" },
  { word: "sun", category: "Nature", difficulty: "easy" },
  { word: "tree", category: "Nature", difficulty: "easy" },
  { word: "house", category: "Objects", difficulty: "easy" },
  { word: "car", category: "Objects", difficulty: "easy" },
  { word: "fish", category: "Animals", difficulty: "easy" },
  { word: "bird", category: "Animals", difficulty: "easy" },
  { word: "apple", category: "Food", difficulty: "easy" },
  { word: "pizza", category: "Food", difficulty: "easy" },
  { word: "star", category: "Nature", difficulty: "easy" },
  { word: "flower", category: "Nature", difficulty: "easy" },
  { word: "boat", category: "Objects", difficulty: "easy" },
  { word: "hat", category: "Objects", difficulty: "easy" },
  { word: "book", category: "Objects", difficulty: "easy" },
  { word: "clock", category: "Objects", difficulty: "easy" },
  { word: "moon", category: "Nature", difficulty: "easy" },
  { word: "heart", category: "Symbols", difficulty: "easy" },
  { word: "key", category: "Objects", difficulty: "easy" },
  { word: "ball", category: "Sports", difficulty: "easy" },
  { word: "cloud", category: "Nature", difficulty: "easy" },
  { word: "cup", category: "Objects", difficulty: "easy" },
  { word: "shoe", category: "Objects", difficulty: "easy" },
  { word: "eye", category: "Body", difficulty: "easy" },
  { word: "hand", category: "Body", difficulty: "easy" },
  { word: "pencil", category: "Objects", difficulty: "easy" },
  { word: "snake", category: "Animals", difficulty: "easy" },
  { word: "bee", category: "Animals", difficulty: "easy" },
  { word: "cake", category: "Food", difficulty: "easy" },
  { word: "chair", category: "Objects", difficulty: "easy" },
  { word: "door", category: "Objects", difficulty: "easy" },
  { word: "window", category: "Objects", difficulty: "easy" },
  { word: "bed", category: "Objects", difficulty: "easy" },
  { word: "table", category: "Objects", difficulty: "easy" },
  { word: "lamp", category: "Objects", difficulty: "easy" },
  { word: "phone", category: "Objects", difficulty: "easy" },
  { word: "banana", category: "Food", difficulty: "easy" },
  { word: "orange", category: "Food", difficulty: "easy" },
  { word: "carrot", category: "Food", difficulty: "easy" },
  { word: "bread", category: "Food", difficulty: "easy" },
  { word: "cheese", category: "Food", difficulty: "easy" },
  { word: "egg", category: "Food", difficulty: "easy" },
  { word: "milk", category: "Food", difficulty: "easy" },
  { word: "spoon", category: "Objects", difficulty: "easy" },
  { word: "fork", category: "Objects", difficulty: "easy" },
  { word: "knife", category: "Objects", difficulty: "easy" },
  { word: "plate", category: "Objects", difficulty: "easy" },
  { word: "bowl", category: "Objects", difficulty: "easy" },
  { word: "bottle", category: "Objects", difficulty: "easy" },
  { word: "box", category: "Objects", difficulty: "easy" },
  { word: "bag", category: "Objects", difficulty: "easy" },
  { word: "pen", category: "Objects", difficulty: "easy" },
  { word: "scissors", category: "Objects", difficulty: "easy" },
  { word: "brush", category: "Objects", difficulty: "easy" },
  { word: "comb", category: "Objects", difficulty: "easy" },
  { word: "mirror", category: "Objects", difficulty: "easy" },
  { word: "soap", category: "Objects", difficulty: "easy" },
  { word: "towel", category: "Objects", difficulty: "easy" },
  { word: "pillow", category: "Objects", difficulty: "easy" },
  { word: "kite", category: "Objects", difficulty: "easy" },

  // Medium
  { word: "elephant", category: "Animals", difficulty: "medium" },
  { word: "bicycle", category: "Objects", difficulty: "medium" },
  { word: "rainbow", category: "Nature", difficulty: "medium" },
  { word: "guitar", category: "Music", difficulty: "medium" },
  { word: "volcano", category: "Nature", difficulty: "medium" },
  { word: "lighthouse", category: "Places", difficulty: "medium" },
  { word: "umbrella", category: "Objects", difficulty: "medium" },
  { word: "penguin", category: "Animals", difficulty: "medium" },
  { word: "spaghetti", category: "Food", difficulty: "medium" },
  { word: "basketball", category: "Sports", difficulty: "medium" },
  { word: "telescope", category: "Objects", difficulty: "medium" },
  { word: "waterfall", category: "Nature", difficulty: "medium" },
  { word: "submarine", category: "Vehicles", difficulty: "medium" },
  { word: "cactus", category: "Nature", difficulty: "medium" },
  { word: "tornado", category: "Nature", difficulty: "medium" },
  { word: "kangaroo", category: "Animals", difficulty: "medium" },
  { word: "skateboard", category: "Sports", difficulty: "medium" },
  { word: "campfire", category: "Nature", difficulty: "medium" },
  { word: "snowman", category: "Seasonal", difficulty: "medium" },
  { word: "treasure chest", category: "Objects", difficulty: "medium" },
  { word: "castle", category: "Places", difficulty: "medium" },
  { word: "dragon", category: "Mythology", difficulty: "medium" },
  { word: "hamburger", category: "Food", difficulty: "medium" },
  { word: "helicopter", category: "Vehicles", difficulty: "medium" },
  { word: "pyramid", category: "Places", difficulty: "medium" },
  { word: "robot", category: "Technology", difficulty: "medium" },
  { word: "ice cream", category: "Food", difficulty: "medium" },
  { word: "mushroom", category: "Nature", difficulty: "medium" },
  { word: "octopus", category: "Animals", difficulty: "medium" },
  { word: "dinosaur", category: "Animals", difficulty: "medium" },
  { word: "giraffe", category: "Animals", difficulty: "medium" },
  { word: "butterfly", category: "Animals", difficulty: "medium" },
  { word: "dolphin", category: "Animals", difficulty: "medium" },
  { word: "crocodile", category: "Animals", difficulty: "medium" },
  { word: "peacock", category: "Animals", difficulty: "medium" },
  { word: "flamingo", category: "Animals", difficulty: "medium" },
  { word: "pineapple", category: "Food", difficulty: "medium" },
  { word: "sandwich", category: "Food", difficulty: "medium" },
  { word: "cupcake", category: "Food", difficulty: "medium" },
  { word: "donut", category: "Food", difficulty: "medium" },
  { word: "popcorn", category: "Food", difficulty: "medium" },
  { word: "pretzel", category: "Food", difficulty: "medium" },
  { word: "sushi", category: "Food", difficulty: "medium" },
  { word: "taco", category: "Food", difficulty: "medium" },
  { word: "airplane", category: "Vehicles", difficulty: "medium" },
  { word: "train", category: "Vehicles", difficulty: "medium" },
  { word: "rocket", category: "Vehicles", difficulty: "medium" },
  { word: "sailboat", category: "Vehicles", difficulty: "medium" },
  { word: "motorcycle", category: "Vehicles", difficulty: "medium" },
  { word: "ambulance", category: "Vehicles", difficulty: "medium" },
  { word: "fire truck", category: "Vehicles", difficulty: "medium" },
  { word: "piano", category: "Music", difficulty: "medium" },
  { word: "drum", category: "Music", difficulty: "medium" },
  { word: "trumpet", category: "Music", difficulty: "medium" },
  { word: "violin", category: "Music", difficulty: "medium" },
  { word: "microphone", category: "Music", difficulty: "medium" },
  { word: "camera", category: "Technology", difficulty: "medium" },
  { word: "computer", category: "Technology", difficulty: "medium" },
  { word: "television", category: "Technology", difficulty: "medium" },
  { word: "headphones", category: "Technology", difficulty: "medium" },
  { word: "ferris wheel", category: "Places", difficulty: "medium" },

  // Hard
  { word: "eclipse", category: "Science", difficulty: "hard" },
  { word: "black hole", category: "Science", difficulty: "hard" },
  { word: "metamorphosis", category: "Science", difficulty: "hard" },
  { word: "constellation", category: "Science", difficulty: "hard" },
  { word: "camouflage", category: "Science", difficulty: "hard" },
  { word: "migration", category: "Science", difficulty: "hard" },
  { word: "hibernation", category: "Science", difficulty: "hard" },
  { word: "photosynthesis", category: "Science", difficulty: "hard" },
  { word: "time travel", category: "Concepts", difficulty: "hard" },
  { word: "déjà vu", category: "Concepts", difficulty: "hard" },
  { word: "nostalgia", category: "Emotions", difficulty: "hard" },
  { word: "karma", category: "Concepts", difficulty: "hard" },
  { word: "paradox", category: "Concepts", difficulty: "hard" },
  { word: "infinity", category: "Concepts", difficulty: "hard" },
  { word: "echo", category: "Concepts", difficulty: "hard" },
  { word: "invisible", category: "Concepts", difficulty: "hard" },
  { word: "democracy", category: "Concepts", difficulty: "hard" },
  { word: "gravity", category: "Science", difficulty: "hard" },
  { word: "evolution", category: "Science", difficulty: "hard" },
  { word: "sarcasm", category: "Concepts", difficulty: "hard" },
  { word: "procrastination", category: "Concepts", difficulty: "hard" },
  { word: "mime", category: "Performance", difficulty: "hard" },
  { word: "jazz", category: "Music", difficulty: "hard" },
  { word: "wifi", category: "Technology", difficulty: "hard" },
  { word: "algorithm", category: "Technology", difficulty: "hard" },
  { word: "quantum", category: "Science", difficulty: "hard" },
  { word: "meditation", category: "Concepts", difficulty: "hard" },
  { word: "reflection", category: "Concepts", difficulty: "hard" },
  { word: "imagination", category: "Concepts", difficulty: "hard" },
  { word: "confusion", category: "Emotions", difficulty: "hard" },
  { word: "frustration", category: "Emotions", difficulty: "hard" },
  { word: "jealousy", category: "Emotions", difficulty: "hard" },
  { word: "curiosity", category: "Emotions", difficulty: "hard" },
  { word: "anxiety", category: "Emotions", difficulty: "hard" },
  { word: "serenity", category: "Emotions", difficulty: "hard" },
  { word: "chaos", category: "Concepts", difficulty: "hard" },
  { word: "harmony", category: "Concepts", difficulty: "hard" },
  { word: "balance", category: "Concepts", difficulty: "hard" },
  { word: "symmetry", category: "Concepts", difficulty: "hard" },
  { word: "perspective", category: "Concepts", difficulty: "hard" },
  { word: "momentum", category: "Science", difficulty: "hard" },
  { word: "orbit", category: "Science", difficulty: "hard" },
  { word: "ecosystem", category: "Science", difficulty: "hard" },
  { word: "biodiversity", category: "Science", difficulty: "hard" },
  { word: "sustainability", category: "Concepts", difficulty: "hard" },
  { word: "innovation", category: "Concepts", difficulty: "hard" },
  { word: "revolution", category: "Concepts", difficulty: "hard" },
  { word: "tradition", category: "Concepts", difficulty: "hard" },
  { word: "culture", category: "Concepts", difficulty: "hard" },
  { word: "dimension", category: "Science", difficulty: "hard" },
  { word: "magnetism", category: "Science", difficulty: "hard" },
  { word: "electricity", category: "Science", difficulty: "hard" },
  { word: "friction", category: "Science", difficulty: "hard" },
  { word: "acceleration", category: "Science", difficulty: "hard" },
  { word: "molecule", category: "Science", difficulty: "hard" },
  { word: "atom", category: "Science", difficulty: "hard" },
  { word: "energy", category: "Science", difficulty: "hard" },
  { word: "velocity", category: "Science", difficulty: "hard" },
  { word: "excitement", category: "Emotions", difficulty: "hard" },
  { word: "inspiration", category: "Concepts", difficulty: "hard" },
];

const byDifficulty: Record<Difficulty, WordEntry[]> = {
  easy: wordBank.filter((w) => w.difficulty === "easy"),
  medium: wordBank.filter((w) => w.difficulty === "medium"),
  hard: wordBank.filter((w) => w.difficulty === "hard"),
};

export function getRandomWord(difficulty: Difficulty): WordEntry {
  const pool = byDifficulty[difficulty];
  return pool[Math.floor(Math.random() * pool.length)];
}
